version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  user_service:
    build: ./user_service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/users
    ports:
      - "8000:8000"
    volumes:
      - ./api_specs:/app/api_specs

  wall_service:
    build: ./wall_service
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
    ports:
      - "8001:8001"
    volumes:
      - ./api_specs:/app/api_specs

volumes:
  pgdata:
  mongodb_data:
